version: '3.8'

services:

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8081:8080"
    depends_on:
      - kafka
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
  postgres:
    image: postgres:17
    container_name: order-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: orderdb
      POSTGRES_USER: order
      POSTGRES_PASSWORD: order
    volumes:
      - pgdata-order:/var/lib/postgresql/data
  payment-postgres:
    image: postgres:17
    container_name: payment-postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: paymentdb
      POSTGRES_USER: payment
      POSTGRES_PASSWORD: payment
    volumes:
      - pgdata-payment:/var/lib/postgresql/data
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    extra_hosts:
      - "host.docker.internal:host-gateway"

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
      - tempo
    volumes:
      - grafana-data:/var/lib/grafana

  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    command: [ "-config.file=/etc/tempo.yml" ]
    volumes:
      - ./tempo.yml:/etc/tempo.yml
    ports:
      - "3200:3200"
      - "9095:9095"

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    command: ["--config=/etc/otel-collector.yml"]
    volumes:
      - ./otel-collector.yml:/etc/otel-collector.yml
    ports:
      - "4317:4317"
      - "4318:4318"

  payment-service:
    build:
      context: .
      dockerfile: payment-service/Dockerfile
    container_name: payment-service
    ports:
      - "8082:8082"
    depends_on:
      - kafka
      - payment-postgres
      - otel-collector
    environment:
      DB_HOST: payment-postgres
      DB_PORT: 5432
      DB_NAME: paymentdb
      DB_USER: payment
      DB_PASSWORD: payment
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      OTEL_ENDPOINT: http://otel-collector:4318/v1/traces


  order-service:
    build:
      context: .
      dockerfile: order-service/Dockerfile
    container_name: order-service
    ports:
      - "8080:8080"
    depends_on:
      - kafka
      - postgres
      - redis
      - otel-collector
    environment:
      DB_HOST: order-postgres
      DB_PORT: 5432
      DB_NAME: orderdb
      DB_USER: order
      DB_PASSWORD: order
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      OTEL_ENDPOINT: http://otel-collector:4318/v1/traces


volumes:
  pgdata-order:
  pgdata-payment:
  grafana-data: