spring:
    application:
        name: order-service

    cache:
        type: redis

    data:
        redis:
            host: localhost
            port: 6379

    kafka:
        bootstrap-servers: localhost:9092

server:
    port: 8080