spring:
    cache:
        type: redis
    data:
        redis:
            host: localhost
            port: 6379
    application:
        name: order-payment-service
    kafka:
        bootstrap-servers: localhost:9092
        producer:
            value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
        consumer:
            group-id: payment-group
            auto-offset-reset: earliest
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
            properties:
                spring.json.trusted.packages: "*"