spring:
    application:
        name: payment-service
    datasource:
        url: jdbc:postgresql://localhost:5433/paymentdb
        username: payment
        password: payment
        driver-class-name: org.postgresql.Driver
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update

outbox:
    retry:
        max-retries: 5
        base-delay-seconds: 30
        max-delay-seconds: 900
        jitter-factor: 0.3

server:
    port: 8082