name: CI

on:
  workflow_dispatch:

  push:
    branches:
      - main

  pull_request:
    branches:
      - main


jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:

      - name: Checkout code
        uses: actions/checkout@v4


      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle


      - name: Build and test
        run: ./gradlew clean test

      - name: Build applications
        run: ./gradlew build

      - name: Build Docker images
        run: docker compose build

      - name: Start infrastructure
        run: docker compose up -d

      - name: Check containers
        run: docker compose ps

      - name: Smoke test
        run: |
          curl --fail http://localhost:8080/actuator/health
          curl --fail http://localhost:8082/actuator/health

      - name: Stop services
        if: always()
        run: docker compose down -v